### ISSUE TITLE
Debian packaging - considerations

### ISSUE THREAD

**Issue by eribertomota** [minfrin/retry#1]
Hi Graham,

I am packaging retry in Debian, as requested here[1].

[1] https://bugs.debian.org/949431

I have some considerations.

1. Now, you can safely remove the debian/ directory. I already sent the package to Debian and it arrived to NEW queue[2].

[2] https://ftp-master.debian.org/new.html

2. Please, consider write 'Copyright (C) 2020 Graham Leggett <minfrin@sharp.fm>' in header of the retry.c file to make easier detect the rights.

3. Please consider change the content of the COPYING file to Apache-2.0 license text.

4. Manpage: please, consider write a manpage from scratch, including all examples from README.md file. You can use txt2man[3] to make it easier. Txt2man is already packaged in Debian and you can see examples of source texts to generate manpages here[4]. Please, make it available in branch master. Currently, is not possible build from master because the manpage is not available there.

[3] https://github.com/mvertes/txt2man
[4] https://salsa.debian.org/debian/txt2man/tree/debian/master/debian/examples.d

5. There are some warnings when running autoreconf:

libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.

Thanks a lot for your work.

Regards,

Eriberto

**Comment by minfrin** [comment]
Thank you for this, busy over the next few days, but will be on it over the weekend.

**Comment by minfrin** [comment]
I made some time - can you verify https://github.com/minfrin/retry/pull/2 and confirm if I've missed anything?

**Comment by eribertomota** [comment]
Hi Graham,

Thanks a lot for all changes.

Sorry for a mistake mine. I wrote right but I didn't check before send the text. So, I will write again, using the 'insert code' feature. The right text is:

`Copyright (C) 2020 Graham Leggett <minfrin@sharp.fm>`

or

`Copyright 2020 Graham Leggett <minfrin@sharp.fm>`

(you can choose the best for you).

A minor change: you wrote 'text2man' in changelog but the right is 'txt2man'.

If you want it, I can test all changes before you release a new version. I can do it quickly. Please, call me after you merge the changes.

Cheers,

Eriberto

**Comment by minfrin** [comment]
All updated - can you cast your eye over it to make sure I updated it correctly?

**Comment by eribertomota** [comment]
I packaged the branch 'debian' to test. I got the following error when building:

```
which txt2man && ./retry --help | txt2man -d 1 -t "retry" -r "retry-1.0.3" > retry.1 || true
 /usr/bin/mkdir -p '/PKGS/retry3/retry-1.0.3/debian/retry/usr/share/man/man1'
 /usr/bin/install -c -m 644 ./retry.1 '/PKGS/retry3/retry-1.0.3/debian/retry/usr/share/man/man1'
/usr/bin/install: cannot stat './retry.1': No such file or directory
make[2]: *** [Makefile:514: install-man1] Error 1
```

So, I suggest to add a check for txt2man presence in configure.ac. After install txt2man and build again, I got some warnings from Debian Build System about the manpage. So I checked the manpage and its content was:

```
.\" Text automatically generated by txt2man
.TH retry  "27 January 2020" "retry-1.0.3" ""
```

Searching in build log, I can see:

```
which txt2man && ./retry --help | txt2man -d 1 -t "retry" -r "retry-1.0.3" > retry.1 || true
/usr/bin/txt2man
/bin/bash: ./retry: No such file or directory
```

Note that I can use a workaround to fix it but this issue will be present for all distributions (Fedora, Arch, Gentoo etc). All distros usespecial environments to build and I think that ./retry will be never found.

I generated the manpage to inspect. You should put two or more spaces between the options and its explanations. See below:

`    -d seconds, --delay=seconds`**[two or more spaces here]**

Finally, I can't build twice in Debian because retry.1 file (previously not existent) is not being removed by Makefile (make clean).

Thanks in advance!

Eriberto

**Comment by minfrin** [comment]
Just to confirm, are you building from a raw checkout of the source tree, or are you building from a tarball created by "make dist"?

In theory autoconf/configure should handle the presence of the man page, and in theory the man page is pregenerated in the tarball for the benefit of cross compile environments where it may not be possible to run the binary.

**Comment by minfrin** [comment]
Thank you for the hint about the options formatting and the two spaces - I was hunting for the pattern and couldn't see it. It's fixed.

**Comment by minfrin** [comment]
> Finally, I can't build twice in Debian because retry.1 file (previously not existent) is
> not being removed by Makefile (make clean).

In theory make clean shouldn't touch the man page, otherwise cross compiling becomes hard. retry.1 is part of the tarball, like Makefile, configure and friends.

**Comment by eribertomota** [comment]
Hum... I tested from repo (git clone). Now I generated the 1.0.3 version from 'make dist' and I packaged it. Is all right now. I think you can close this issue.

When the version 1.0.2  has been approved by FTP-Master Team in Debian, I will sent a new version (1.0.3, released by you in next minutes/days).

FTP-Master analyses new packages from a queue (it can take between 1 day and 3 months). After this, my next uploads will arrive in Debian in few minutes. Ubuntu will always take the package from Debian.

Cheers,

Eriberto

**Comment by minfrin** [comment]
Thank you for this - it is greatly appreciated.

I just ran everything through the COPR builds and all is fine. I have made a release of retry-1.0.3 here:

https://github.com/minfrin/retry/releases/tag/retry-1.0.3
