### ISSUE TITLE
Staggered delays not working

### ISSUE THREAD

**Issue by knocte** [minfrin/retry#14]
I put this in a shell script:

```
#!/usr/bin/env bash
set -euxo pipefail

for pkg in "$@"
do
    retry --until=success --times=4 --delay "60,300,600,999" -- sudo DEBIAN_FRONTEND=noninteractive apt install --yes "$pkg"
done
```

And, when executing it, I get:

```
Run ./scripts/CI/linux_pkg_install.sh fsharp nunit-console
  ./scripts/CI/linux_pkg_install.sh fsharp nunit-console
  shell: /usr/bin/bash -e {0}
+ for pkg in "$@"
+ retry --until=success --times=4 --delay 60,300,600,999 -- sudo DEBIAN_FRONTEND=noninteractive apt install --yes fsharp
Delay must be bigger or equal to 0.


NAME
  retry - Repeat command until a criteria is met, usually success.

SYNOPSIS
  retry [-v] [-h] [-u until] [-w while] command ...
```

**Comment by minfrin** [comment]
Can you confirm the version you're using?

Staggered delay is new in v1.0.5 and up.

**Comment by minfrin** [comment]
Also, I see you're using --times= but --delay with no equals, seems to be an odd inconsistency, not sure if it matters.

**Comment by knocte** [comment]
> Staggered delay is new in v1.0.5 and up.

Using what ubuntu bundles, which apparently in v22.04 is v1.0.4. How can v.1.0.4 not have staggered delays when they are mentioned in the help output and in the error message "Delay must be bigger or equal to 0"? You mean because there was a bug in 1.0.4 related to delays?

**Comment by minfrin** [comment]
> Using what ubuntu bundles, which apparently in v22.04 is v1.0.4. How can v.1.0.4 not have staggered delays when they are mentioned in the help output and in the error message "Delay must be bigger or equal to 0"? You mean because there was a bug in 1.0.4 related to delays?

I wrote staggered delays myself two weeks ago: https://github.com/minfrin/retry/pull/9

The version you're using was released three years ago, and supported a single delay. The next version has been picked up by debian already, and should be available in ubuntu soon.

**Comment by knocte** [comment]
Ah yeah of course, I don't know what I was thinking. Thanks
