### ISSUE TITLE
command line parsing on retry 1.04 

### ISSUE THREAD

**Issue by kanliot** [minfrin/retry#3]
uh, I'm glad I was able to easily install `retry` (debian 10-backports) 

but does 1.04 work with commands that need options?

example:

    retry echo e # works
    retry echo -n e # retry shows uh the documentation for retry

I've been trying different things, and I don't see how it's supposed to work, although i haven't tried the curl example, since i don't ahve a webserver on localhost. 

I finished my `ebay-alarm` script last night, and i'd like it to work with this program
https://github.com/kanliot/ebay-alarm

**Comment by minfrin** [comment]
It seems to be a quirk of getopt_long() - you need to do this:

    Little-Net:retry-trunk minfrin$ ./retry -- echo -n e
    eLittle-Net:retry-trunk minfrin$

**Comment by kanliot** [comment]
yeah works on 1.04.  

thank you very much!

**Comment by wconrad** [comment]
I don't know that it's even a getopt_long() quirk that `--` is needed.  I think it's standard option parsing in Linux, and maybe even a Posix standard.  Maybe it's worth mentioning in the README, since it caught at least one user by surprise.

**Comment by pabloab** [comment]
Would be great to add this `--` bit on the readme/documentation/man page, might not be too obvious. Maybe this hint instead of the full man page when `retry: unrecognized option '--option-of-executed-command'`.
