### ISSUE TITLE
Merge outstanding pull requests

### ISSUE THREAD

**Issue by hongkongkiwi** [minfrin/retry#8]
There's a couple of great pull requests to add exponential backoff and also better handling of cli args.

Is it possible to merge these?

**Comment by gajus** [comment]
CC @minfrin Would really appreciate https://github.com/minfrin/retry/pull/4 getting merged

**Comment by rpearce** [comment]
@minfrin It seems this issue is all resolved?

**Comment by minfrin** [comment]
Issues that just say "merge outstanding pull requests" aren't that helpful to open source people - it's basically another way of saying "give us free labour". Rather comment under the relevant tickets, along with additional details like testing you've done. This highlights where there is a need, and takes the pressure off.

**Comment by rpearce** [comment]
I agree! Thank you for this tool, it's very helpful.
